#pragma once
#include <string>
#include <unordered_map>
#include <vector>
#include <Geode/Geode.hpp>

class Localization {
public:
    enum class Language {
        SPANISH,
        ENGLISH,
        PORTUGUESE,
        FRENCH,
        GERMAN,
        RUSSIAN,
        JAPANESE
    };

    static Localization& get() {
        static Localization instance;
        return instance;
    }

    static std::vector<Language> getAvailableLanguages() {
        return {
            Language::SPANISH,
            Language::ENGLISH,
            Language::PORTUGUESE,
            Language::FRENCH,
            Language::GERMAN,
            Language::RUSSIAN,
            Language::JAPANESE,
        };
    }

    static std::string languageToId(Language lang) {
        switch (lang) {
            case Language::SPANISH: return "spanish";
            case Language::ENGLISH: return "english";
            case Language::PORTUGUESE: return "portuguese";
            case Language::FRENCH: return "french";
            case Language::GERMAN: return "german";
            case Language::RUSSIAN: return "russian";
            case Language::JAPANESE: return "japanese";
        }
        return "english";
    }

    static Language languageFromId(std::string const& id) {
        if (id == "spanish") return Language::SPANISH;
        if (id == "portuguese") return Language::PORTUGUESE;
        if (id == "french") return Language::FRENCH;
        if (id == "german") return Language::GERMAN;
        if (id == "russian") return Language::RUSSIAN;
        if (id == "japanese") return Language::JAPANESE;
        return Language::ENGLISH;
    }

    static std::string languageDisplayName(Language lang) {
        switch (lang) {
            case Language::SPANISH: return "Espanol";
            case Language::ENGLISH: return "English";
            case Language::PORTUGUESE: return "Portugues";
            case Language::FRENCH: return "Francais";
            case Language::GERMAN: return "Deutsch";
            case Language::RUSSIAN: return "Russkiy";
            case Language::JAPANESE: return "Nihongo";
        }
        return "English";
    }

    void setLanguage(Language lang, bool persist = true) {
        m_currentLanguage = lang;
        if (!persist) return;

        auto id = languageToId(lang);
        geode::Mod::get()->setSavedValue("language", id);
        geode::Mod::get()->setSettingValue<std::string>("language", id);
    }

    Language getLanguage() const {
        return m_currentLanguage;
    }

    std::string getCurrentLanguageId() const {
        return languageToId(m_currentLanguage);
    }

    std::string getCurrentLanguageDisplayName() const {
        return languageDisplayName(m_currentLanguage);
    }

    std::string getString(std::string const& key) const {
        auto const& translations = translationsFor(m_currentLanguage);
        auto it = translations.find(key);
        if (it != translations.end()) {
            return it->second;
        }
        auto enIt = m_english.find(key);
        if (enIt != m_english.end()) {
            return enIt->second;
        }
        return key; // Fallback to key if not found
    }

    void loadFromSettings() {
        std::string langStr = geode::Mod::get()->getSavedValue<std::string>("language", "");
        if (langStr.empty()) {
            langStr = geode::Mod::get()->getSettingValue<std::string>("language");
        }
        if (langStr.empty()) {
            langStr = "english";
        }

        m_currentLanguage = languageFromId(langStr);
    }

private:
    Localization() {
        loadFromSettings();
        initTranslations();
    }

    std::unordered_map<std::string, std::string> const& translationsFor(Language lang) const {
        switch (lang) {
            case Language::SPANISH: return m_spanish;
            case Language::ENGLISH: return m_english;
            case Language::PORTUGUESE: return m_portuguese;
            case Language::FRENCH: return m_french;
            case Language::GERMAN: return m_german;
            case Language::RUSSIAN: return m_russian;
            case Language::JAPANESE: return m_japanese;
        }
        return m_english;
    }

    void initTranslations() {
        // Spanish translations
        m_spanish = {
            // CapturePreviewPopup
            {"preview.title", "Vista previa"},
            {"preview.borders_removed", "Ya se eliminaron los bordes"},
            {"preview.no_borders", "No se detectaron bordes negros"},
            {"preview.borders_deleted", "Bordes eliminados"},
            {"preview.fill_mode_active", "Rellenar (activo)"},
            {"preview.fit_mode_active", "Ajustar (activo)"},
            {"preview.player_toggle_error", "No se puede alternar visibilidad del jugador"},
            {"preview.no_image", "No hay imagen para descargar"},
            {"preview.folder_error", "Error al crear carpeta de descargas"},
            {"preview.downloaded", "Miniatura descargada!"},
            {"preview.save_error", "Error al guardar archivo"},
            {"preview.process_error", "Error al procesar imagen"},
            {"preview.res_changed", "Resolucion cambiada a {}"},
            {"preview.recapturing", "Recapturando..."},

            // CaptureEditPopup
            {"edit.capture_title", "Editar"},
            {"edit.toggle_player", "Ocultar jugador"},
            {"edit.hide_player1", "Ocultar P1"},
            {"edit.show_player1", "Mostrar P1"},
            {"edit.hide_player2", "Ocultar P2"},
            {"edit.show_player2", "Mostrar P2"},
            {"edit.crop_borders", "Recortar bordes"},
            {"edit.toggle_fill", "Modo de vista"},
            {"edit.download", "Descargar"},
            {"edit.edit_layers", "Editar capas"},

            // CaptureLayerEditorPopup
            {"layers.title", "Editar Capas"},
            {"layers.player1", "Jugador 1"},
            {"layers.player2", "Jugador 2"},
            {"layers.effects", "Efectos (Shaders)"},
            {"layers.recapture", "Recapturar"},
            {"layers.done", "Listo"},
            {"layers.restore_all", "Restaurar"},
            {"layers.restored", "Capas restauradas"},
            {"layers.recapturing", "Recapturando..."},
            {"layers.recapture_error", "Error al recapturar"},
            {"layers.no_playlayer", "PlayLayer no disponible"},
            {"layers.beta_title", "Funcion Beta"},
            {"layers.beta_message", "<cr>Esta funcion esta en beta</c> y puede tener <cy>muchos errores</c>.\nAlgunas capas pueden no funcionar correctamente.\n\nEstas seguro de que quieres continuar?"},
            {"layers.beta_confirm", "Continuar"},
            {"layers.beta_cancel", "Cancelar"},

            // Keybinds
            {"keybind.capture_triggered", "Captura activada"},
            {"keybind.capture_paused", "No se puede capturar en pausa"},

            // PlayLayer & PauseLayer
            {"capture.action_name", "Capturar Miniatura"},
            {"capture.action_desc", "Toma una captura del nivel actual"},
            {"capture.error", "Error al capturar miniatura"},
            {"capture.process_error", "Error al procesar miniatura"},
            {"capture.save_png_error", "Error al guardar PNG"},
            {"capture.read_png_error", "Error al leer PNG"},
            {"capture.upload_error", "Error al subir miniatura"},
            {"capture.uploading", "Subiendo miniatura al servidor..."},
            {"capture.upload_success", "Miniatura subida exitosamente!"},
            {"capture.suggested", "Miniatura sugerida"},
            {"capture.verifying", "Verificando permisos..."},
            {"capture.uploading_suggestion", "Subiendo sugerencia..."},

            // PauseLayer specific
            {"pause.no_local_thumb", "No hay miniatura local para subir"},
            {"pause.only_moderators", "Solo moderadores pueden subir miniaturas"},
            {"pause.access_error", "Error al acceder a miniatura local"},
            {"pause.read_error", "Error al leer miniatura local"},
            {"pause.gif_disabled", "Grabacion GIF deshabilitada temporalmente"},
            {"pause.playlayer_error", "Error: PlayLayer no disponible"},
            {"pause.capture_error", "Error al iniciar captura"},
            {"pause.gif_open_error", "Error: No se pudo abrir el GIF"},
            {"pause.gif_read_error", "Error: No se pudo leer el GIF"},
            {"pause.gif_texture_error", "Error: No se pudo crear textura del GIF"},
            {"pause.gif_uploading", "Subiendo GIF al servidor..."},
            {"pause.gif_uploaded", "GIF subido correctamente"},
            {"pause.gif_upload_error", "No se pudo subir el GIF"},
            {"pause.gif_process_error", "Error al procesar GIF"},
            {"pause.file_open_error", "Error: No se pudo abrir el archivo"},
            {"pause.png_invalid", "Error: Archivo PNG invalido"},
            {"pause.process_thumbnail_error", "No se pudo procesar la miniatura"},

            // ProfilePage
            {"profile.username_error", "No se pudo obtener tu nombre de usuario"},
            {"profile.verified", "Verificado"},
            {"profile.verified_msg", "Eres un <cg>moderador aprobado</c>! Ahora puedes subir y verificar miniaturas."},
            {"profile.not_verified", "No verificado"},
            {"profile.not_verified_msg", "No estas en la lista de moderadores aprobados."},
            {"profile.image_open_error", "No se pudo abrir imagen"},
            {"profile.video_open_error", "No se pudo abrir video"},
            {"profile.texture_error", "No se pudo crear textura"},
            {"profile.saved", "Miniatura de perfil guardada"},
            {"profile.no_image_selected", "No se selecciono imagen"},
            {"profile.invalid_image_data", "Datos de imagen invalidos"},
            {"profile.access_denied", "Acceso denegado"},
            {"profile.moderators_only", "Solo los moderadores pueden acceder al centro de verificacion."},

            // LevelInfoLayer
            {"level.title", "Miniatura del nivel"},
            {"level.no_thumbnail", "No hay miniatura"},
            {"level.open_error", "Error al abrir miniatura"},
            {"level.read_error", "Error al leer miniatura"},
            {"level.create_error", "Error al crear imagen"},
            {"level.save_error", "Error al guardar imagen"},
            {"level.saved", "Imagen guardada correctamente"},
            {"level.no_local", "No hay miniatura local"},
            {"level.cant_open", "No se pudo abrir la miniatura"},
            {"level.corrupt", "Miniatura corrupta"},
            {"level.report_button", "Reportar"},
            {"level.delete_button", "Borrar miniatura"},
            {"level.accept_button", "Aceptar"},
            {"level.download_button", "Descargar"},

            // VerificationQueuePopup
            {"queue.title", "Centro de verificacion"},
            {"queue.verify_tab", "verificar thumbnails"},
            {"queue.update_tab", "actualizacion"},
            {"queue.report_tab", "reportes"},
            {"queue.no_items", "No hay elementos"},
            {"queue.select_item", "Selecciona un elemento"},
            {"queue.open_button", "Abrir"},
            {"queue.accept_button", "Aceptar"},
            {"queue.reject_button", "Rechazar"},
            {"queue.view_report", "Ver reporte"},
            {"queue.report_reason", "Motivo del reporte"},
            {"queue.close", "Cerrar"},
            {"queue.no_local", "No hay miniatura local"},
            {"queue.cant_open", "No se pudo abrir miniatura"},
            {"queue.corrupt", "Miniatura corrupta"},
            {"queue.read_error", "Error al leer miniatura"},
            {"queue.create_error", "Error al crear imagen"},
            {"queue.png_error", "Error al generar PNG"},
            {"queue.png_read_error", "Error al leer PNG"},
            {"queue.accepting", "Aceptando y subiendo al servidor..."},
            {"queue.accepted", "Miniatura aceptada y sincronizada"},
            {"queue.accept_error", "Error al sincronizar con servidor"},
            {"queue.rejecting", "Rechazando en servidor..."},
            {"queue.rejected", "Miniatura rechazada y sincronizada"},
            {"queue.reject_error", "Error al sincronizar rechazo"},

            // AddModeratorPopup
            {"addmod.enter_username", "Ingresa un nombre de usuario"},
            {"addmod.success_title", "Agregado"},
            {"addmod.success_msg", "Moderador agregado exitosamente"},
            {"addmod.error_title", "Error"},
            {"addmod.error_msg", "No se pudo agregar al moderador"},
            {"addmod.title", "Gestionar Moderadores"},
            {"addmod.add_btn", "Agregar"},
            {"addmod.enter_username_label", "Nuevo moderador:"},
            {"addmod.loading_mods", "Cargando moderadores..."},
            {"addmod.no_mods", "No hay moderadores"},
            {"addmod.remove_btn", "Quitar"},
            {"addmod.remove_confirm_title", "Quitar Moderador"},
            {"addmod.remove_confirm_msg", "Quitar a <cy>{}</c> como moderador?"},
            {"addmod.remove_success", "Moderador eliminado exitosamente"},
            {"addmod.remove_error", "No se pudo eliminar al moderador"},
            {"general.cancel", "Cancelar"},

            // BulkUploadPopup
            {"bulk.title", "Subida Masiva"},
            {"bulk.select_folder_label", "Selecciona una carpeta con thumbnails"},
            {"bulk.progress_label", "0 / 0 thumbnails"},
            {"bulk.info_text", "Los archivos deben tener el formato:\nlevelID.png (ej: 12345.png)\n\nSolo se subiran thumbnails de\nniveles que no tengan ya uno."},
            {"bulk.scanning", "Escaneando carpeta..."},

            // GIFUploadPopup
            {"gif.upload.title", "GIF grabado"},
            {"gif.label", "GIF"},
            {"daily.title", "Establecer nivel destacado"},
            {"daily.set_daily", "Poner Daily"},
            {"daily.set_weekly", "Poner Weekly"},
            {"daily.success_daily_title", "Exito"},
            {"daily.success_daily_msg", "Nivel establecido como Daily!"},
            {"daily.error_daily_title", "Error"},
            {"daily.error_daily_msg", "Fallo al establecer Daily."},
            {"daily.success_weekly_title", "Exito"},
            {"daily.success_weekly_msg", "Nivel establecido como Weekly!"},
            {"daily.error_weekly_title", "Error"},
            {"daily.error_weekly_msg", "Fallo al establecer Weekly."},

            // ThumbnailViewPopup
            {"thumbview.title", "Miniatura"},

            // VerificationQueuePopup
            {"queue.banned_btn", "Baneados"},
            {"queue.level_id", "Nivel {}"},
            {"queue.claimed_by_you", "Reclamado por ti"},
            {"queue.claimed_by_user", "Reclamado por {}"},
            {"queue.view_btn", "Ver"},
            {"queue.view_thumb", "Ver Miniatura"},
            {"queue.claim_btn", "Reclamar"},
            {"queue.unclaim_btn", "Desreclamar"},
            {"queue.accept_btn", "Aceptar"},
            {"queue.reject_btn", "Rechazar"},
            {"queue.verified_by", "Verificado por {}"},
            {"queue.reported_by", "Reportado por {}"},
            {"queue.reason", "Motivo: {}"},
            {"queue.ignore_btn", "Ignorar"},
            {"queue.delete_btn", "Borrar"},
            {"queue.keep_btn", "Mantener"},
            {"queue.claiming", "Reclamando nivel..."},
            {"queue.claimed", "Nivel reclamado"},
            {"queue.claim_error", "Error: {}"},

            // ButtonEditOverlay
            {"edit.buttons_title", "Editar Botones"},
            {"edit.accept", "Aceptar"},
            {"edit.reset", "Reiniciar"},
            {"edit.scale", "Escala:"},
            {"edit.opacity", "Opacidad:"},
            {"menu_layout.title", "Editor de Menu Principal"},
            {"menu_layout.save", "Guardar"},
            {"menu_layout.cancel", "Cancelar"},
            {"menu_layout.save_preset", "Guardar Slot"},
            {"menu_layout.load_preset", "Cargar Slot"},
            {"menu_layout.reset_selected", "Reset Boton"},
            {"menu_layout.reset_all", "Reset Todo"},
            {"menu_layout.layers_title", "Capas"},
            {"menu_layout.layer", "Capa"},
            {"menu_layout.layer_up", "Subir"},
            {"menu_layout.layer_down", "Bajar"},
            {"menu_layout.edit_selected", "Editar"},
            {"menu_layout.link_selected", "Link"},
            {"menu_layout.unlink_selected", "Unlink"},
            {"menu_layout.hide_selected", "Ocultar"},
            {"menu_layout.delete_selected", "Borrar"},
            {"menu_layout.scale_down", "Tam -"},
            {"menu_layout.scale_up", "Tam +"},
            {"menu_layout.hint", "Arrastra para mover. Grip verde = escala fija. Boton Escala = modo libre. Azul +/- = opacidad. Tam +/- = agrandador rapido. Roja X = ocultar/mostrar. Esc cancela."},
            {"menu_layout.none_selected", "Toca un boton del menu principal para editarlo"},
            {"menu_layout.status", "Boton: {}  X:{:.0f} Y:{:.0f}  Escala:{:.2f}x  Opacidad:{:.0f}%"},
            {"menu_layout.saved", "Layout del menu guardado"},
            {"menu_layout.context_popup_hint", "Ajusta opacidad, color y fuente del elemento seleccionado."},
            {"menu_layout.context_font", "Fuente"},
            {"menu_layout.context_pick_font", "Elegir"},
            {"menu_layout.presets_title_save", "Guardar Preset"},
            {"menu_layout.presets_title_load", "Cargar Preset"},
            {"menu_layout.presets_hint_save", "Elige un slot para guardar el layout actual."},
            {"menu_layout.presets_hint_load", "Elige un slot para cargar todo el layout."},
            {"menu_layout.presets_page", "Pagina {}/{}"},
            {"menu_layout.presets_slot", "Slot {}"},
            {"menu_layout.presets_empty", "Vacio"},
            {"menu_layout.presets_items", "{} elementos"},
            {"menu_layout.presets_empty_slot", "Ese slot esta vacio"},
            {"menu_layout.preset_saved", "Preset guardado en slot {}"},
            {"menu_layout.preset_loaded", "Preset cargado desde slot {}"},
            {"menu_layout.preset_overwrite_title", "Sobrescribir Preset"},
            {"menu_layout.preset_overwrite_body", "El slot <cy>{}</c> ya tiene un preset. Sobrescribirlo?"},
            {"menu_layout.preset_overwrite_confirm", "Sobrescribir"},
            {"menu_layout.preset_load_title", "Cargar Preset"},
            {"menu_layout.preset_load_body", "Cargar el preset del slot <cy>{}</c>? Esto reemplazara el layout actual del editor."},
            {"menu_layout.preset_load_confirm", "Cargar"},
            {"menu_layout.reset_done", "Botones restaurados a su layout base"},
            {"menu_layout.reset_saved", "Layout guardado borrado y botones restaurados"},
            {"menu_layout.draw_add_rect", "Rect"},
            {"menu_layout.draw_add_round", "Curvo"},
            {"menu_layout.draw_add_circle", "Circulo"},
            {"menu_layout.draw_edit_shape", "Editar Draw"},
            {"menu_layout.draw_shape_label", "Paimon Draw"},
            {"menu_layout.draw_shape_popup_title", "Editar Paimon Draw"},
            {"menu_layout.draw_shape_popup_hint", "Ajusta forma, color, tamano y opacidad. Se guarda en el layout y en los slots."},
            {"menu_layout.draw_shape_kind", "Forma"},
            {"menu_layout.draw_shape_kind_rect", "Rectangulo"},
            {"menu_layout.draw_shape_kind_round", "Curvo"},
            {"menu_layout.draw_shape_kind_circle", "Circulo"},
            {"menu_layout.draw_shape_cycle", "Cambiar"},
            {"menu_layout.draw_shape_color", "Color"},
            {"menu_layout.draw_shape_pick_color", "Elegir"},
            {"menu_layout.draw_shape_width", "Ancho"},
            {"menu_layout.draw_shape_height", "Alto"},
            {"menu_layout.draw_shape_radius", "Radio"},
            {"menu_layout.draw_shape_opacity", "Opacidad"},
            {"menu_layout.draw_shape_radius_disabled", "N/A"},

            // ForYou
            {"foryou.title", "Para Ti"},
            {"foryou.tab", "Para Ti"},
            {"foryou.not_enough_data", "Juega mas niveles para desbloquear recomendaciones"},
            {"foryou.no_results", "No se encontraron niveles recomendados"},
            {"foryou.tags_prompt_title", "Level Tags"},
            {"foryou.tags_prompt", "Instala <cy>Level Tags</c> para mejorar tus recomendaciones con tags de niveles!"},
            {"foryou.tags_download", "Descargar"},
            {"foryou.fav_creator_added", "Creador agregado a favoritos"},
            {"foryou.fav_creator_removed", "Creador eliminado de favoritos"},
            {"foryou.fav_level_added", "Nivel agregado a favoritos"},
            {"foryou.fav_level_removed", "Nivel eliminado de favoritos"},
            {"foryou.prefs_title", "Que niveles te gustan?"},
            {"foryou.prefs_subtitle", "Elige tus preferencias para mejorar recomendaciones"},
            {"foryou.prefs_difficulty", "Dificultad"},
            {"foryou.prefs_gamemode", "Modo de juego"},
            {"foryou.prefs_classic", "Clasico"},
            {"foryou.prefs_platformer", "Platformer"},
            {"foryou.prefs_both", "Ambos"},
            {"foryou.prefs_confirm", "Confirmar"},
            {"foryou.prefs_length", "Duracion"},
            {"foryou.prefs_tiny", "Minima"},
            {"foryou.prefs_short", "Corta"},
            {"foryou.prefs_medium", "Media"},
            {"foryou.prefs_long", "Larga"},
            {"foryou.prefs_xl", "XL"},
            {"foryou.prefs_any_length", "Cualquiera"},
            {"foryou.prefs_star_rated", "Con estrellas"},
            {"foryou.prefs_featured", "Destacados"},
            {"foryou.prefs_epic", "Epicos"},
            {"foryou.prefs_demon_diff", "Demon dificultad"},
            {"foryou.prefs_filters", "Filtros"},
            {"foryou.info_difficulty_title", "Dificultad"},
            {"foryou.info_difficulty_desc", "Elige el nivel de <cy>dificultad</c> que prefieres.\nAfecta las recomendaciones que se muestran\nen tu feed <cg>Para Ti</c>."},
            {"foryou.info_demon_title", "Dificultad Demon"},
            {"foryou.info_demon_desc", "Solo aplica si seleccionaste <cy>Demon</c> arriba.\nElige la subdificultad preferida:\n<cy>Easy, Medium, Hard, Insane, Extreme</c>\no <cg>Cualquiera</c> para no filtrar."},
            {"foryou.info_mode_title", "Modo de Juego"},
            {"foryou.info_mode_desc", "<cy>Clasico</c>: niveles tradicionales.\n<cy>Platformer</c>: niveles con estilo plataforma.\n<cy>Ambos</c>: sin preferencia de modo."},
            {"foryou.info_length_title", "Duracion"},
            {"foryou.info_length_desc", "Duracion aproximada del nivel:\n<cy>Minima, Corta, Media, Larga, XL</c>\no <cg>Cualquiera</c> para no filtrar."},
            {"foryou.info_filters_title", "Filtros de Calidad"},
            {"foryou.info_filters_desc", "<cy>Con estrellas</c>: niveles rated.\n<cy>Destacados</c>: niveles Featured.\n<cy>Epicos</c>: niveles con rating Epic."},
            {"foryou.prefs_rating", "Calidad"},
            {"foryou.prefs_rating_star", "Con estrellas"},
            {"foryou.prefs_rating_featured", "Destacado"},
            {"foryou.prefs_rating_epic", "Epico"},
            {"foryou.prefs_rating_legendary", "Legendario"},
            {"foryou.prefs_rating_mythic", "Mitico"},
            {"foryou.info_rating_title", "Calidad del Nivel"},
            {"foryou.info_rating_desc", "Toca el icono para ciclar entre tiers de calidad:\n<cy>Con estrellas</c> → <cy>Destacado</c> → <cy>Epico</c> →\n<cy>Legendario</c> → <cy>Mitico</c>.\nCada tier incluye los anteriores."},
            {"foryou.fav_levels_title", "Niveles Favoritos"},
            {"foryou.coming_soon", "Proximamente"},

            // LeaderboardsLayer
            {"leaderboard.daily", "Diario"},
            {"leaderboard.weekly", "Semanal"},
            {"leaderboard.all_time", "Global"},
            {"leaderboard.creators", "Creadores"},
            {"leaderboard.error", "Error"},
            {"leaderboard.read_error", "Error al leer respuesta"},
            {"leaderboard.load_error", "Error al cargar leaderboard: {}"},
            {"leaderboard.parse_error", "Error al procesar JSON"},
            {"leaderboard.server_error", "Error del servidor"},
            {"leaderboard.invalid_format", "Formato de datos invalido"},
            {"leaderboard.loading", "Cargando..."},
            {"leaderboard.unknown", "Desconocido"},
            {"mods.title", "Moderadores de Paimbnails"},

            // CommunityHubLayer
            {"community.title", "Centro Comunitario"},
            {"community.tab_mods", "Moderadores"},
            {"community.tab_creators", "Top Creadores"},
            {"community.tab_thumbnails", "Top Miniaturas"},
            {"community.tab_compat_mods", "Mods Compat."},
            {"community.compat_mods_title", "Mods Compatibles"},
            {"community.compat_mods_version", "Disponible para la version 1.0.1"},
            {"community.compat_mods_desc", "Lista de mods compatibles con Paimbnails"},
            {"community.compat_mods_soon", "Mas mods proximamente..."},
            // CommunityHub info buttons
            {"community.info_mods_title", "Moderadores"},
            {"community.info_mods_body", "Lista de los <cy>moderadores oficiales</c> de Paimbnails.\nPueden subir, verificar y gestionar miniaturas.\nLos <cr>Admins</c> tienen permisos adicionales."},
            {"community.info_creators_title", "Top Creadores"},
            {"community.info_creators_body", "Ranking de los creadores con mas miniaturas subidas y mejor valoradas.\nSube miniaturas de tus niveles para aparecer en esta lista!"},
            {"community.info_thumbs_title", "Top Miniaturas"},
            {"community.info_thumbs_body", "Las miniaturas mejor valoradas por la comunidad.\nPuedes votar las miniaturas desde la pantalla de nivel."},
            {"community.info_compat_title", "Mods Compatibles"},
            {"community.info_compat_body", "Mods de Geometry Dash compatibles con Paimbnails.\nDisponible a partir de la version <cy>1.0.1</c>."},
            {"community.loading", "Cargando..."},
            {"community.error", "Error al cargar datos"},
            {"community.no_data", "Sin datos disponibles"},
            {"community.uploads", "Subidas"},
            {"community.avg_rating", "Rating Prom."},
            {"community.rating", "Rating"},
            {"community.votes", "Votos"},
            {"community.by", "por"},
            {"community.admin", "Admin"},
            {"community.mod", "Mod"},
            {"community.level", "Nivel"},
            {"leaderboard.no_refreshes", "No hay mas recargas disponibles hoy!"},
            {"leaderboard.no_gamemanager", "No se pudo obtener GameManager"},
            {"leaderboard.empty_username", "Nombre de usuario vacio"},
            {"leaderboard.no_image", "No se selecciono imagen"},
            {"leaderboard.png_open_error", "No se pudo abrir PNG"},
            {"leaderboard.profile_saved_local", "Perfil guardado localmente (subida al servidor deshabilitada)"},
            {"leaderboard.uploading_profile", "Subiendo perfil..."},
            {"leaderboard.profile_uploaded", "Perfil subido"},
            {"leaderboard.profile_error", "Error al subir perfil"},
            {"leaderboard.unknown_error", "Error desconocido"},
            {"leaderboard.synced", "Sincronizado con el servidor!"},

            // GIFRecordSettingsPopup
            {"gif.start", "Iniciar"},

            // General
            {"general.error", "Error"},
            {"general.ok", "OK"},
            {"general.close", "Cerrar"},

            // Missing keys added
            {"level.no_thumbnail_text", "No hay miniatura"},
            {"level.saving_mod_folder", "Guardando en carpeta del mod..."},
            {"level.error_prefix", "Error: "},
            {"level.delete_moderator_only", "Solo moderadores pueden borrar miniaturas"},
            {"level.deleting_server", "Borrando miniatura del servidor..."},
            {"level.deleted_server", "Miniatura eliminada del servidor"},
            {"level.delete_error", "Error al borrar: "},
            {"level.accepting", "Aceptando miniatura..."},
            {"level.accepted", "¡Miniatura aceptada!"},
            {"level.accept_error", "Error al aceptar: "},
            {"level.no_local_thumb", "No hay miniatura local"},
            {"level.png_error", "Error al generar PNG"},
            {"level.saved_local_server_disabled", "Miniatura guardada localmente (servidor deshabilitado)"},
            {"level.account_required", "Tienes que tener cuenta para subir"},
            {"level.no_permissions", "No tienes permisos"},
            {"level.admin_only_high_votes", "Solo administradores pueden borrar miniaturas con +100 votos"},
            {"level.confirm_delete_title", "Borrar Miniatura"},
            {"level.confirm_delete_msg", "Estas seguro de que quieres borrar esta miniatura? Esto tambien eliminara los puntos de rating del creador."},
            {"level.thumbnail_deleted", "Miniatura borrada"},

            // Report Popup
            {"report.title", "Reportar Miniatura"},
            {"report.cancel", "Cancelar"},
            {"report.send", "Enviar"},
            {"report.placeholder", "Escribe aqui..."},
            {"report.empty_reason", "Debes especificar una razon"},
            {"report.sent_synced", "Reporte enviado y sincronizado: "},
            {"report.saved_local", "Reporte guardado localmente (sin conexion)"},

            // PauseLayer
            {"pause.gif_not_supported", "Archivos GIF no soportados en esta plataforma"},
            {"pause.process_image_error", "Error: No se pudo procesar la imagen"},
            {"pause.create_texture_error", "Error: No se pudo crear textura"},
            {"pause.init_texture_error", "Error: No se pudo inicializar textura"},
            {"pause.username_error", "Error: No se pudo obtener nombre de usuario"},
            {"pause.gif_recording_started", "Grabacion GIF iniciada"},

            // Ban System
            {"ban.list.title", "Baneados"},
            {"ban.list.loading", "Cargando..."},
            {"ban.list.empty", "Sin baneos"},
            {"ban.list.unban_btn", "Desbanear"},
            {"ban.info.no_info", "Sin informacion disponible."},
            {"ban.info.reason", "Razon"},
            {"ban.info.by", "Por"},
            {"ban.info.date", "Fecha"},
            {"ban.info.title", "Detalles del Baneo"},
            {"ban.unban.title", "Desbanear Usuario"},
            {"ban.unban.confirm", "¿Estas seguro de desbanear a <cy>{}</c>?"},
            {"ban.unban.success", "Usuario desbaneado"},
            {"ban.unban.error", "Error al desbanear"},
            {"ban.popup.title", "Banear Usuario"},
            {"ban.popup.user", "Usuario: {}"},
            {"ban.popup.placeholder", "Razon del baneo..."},
            {"ban.popup.ban_btn", "Banear"},
            {"ban.popup.enter_reason", "Ingresa una razon"},
            {"ban.popup.success", "Usuario baneado"},
            {"ban.popup.error", "Error al banear"},
            {"ban.profile.mod_only", "Solo moderadores/admins"},
            {"ban.profile.self_ban", "No puedes banearte"},
            {"ban.profile.read_error", "No se pudo leer el usuario"},

            // Profile Music
            {"music.title", "Musica de Perfil"},
            {"music.load_song", "Cargar"},
            {"music.play_preview", "Reproducir"},
            {"music.stop_preview", "Detener"},
            {"music.save", "Guardar"},
            {"music.delete", "Eliminar"},
            {"music.song_id_placeholder", "ID de cancion..."},
            {"music.no_song_loaded", "Sin cancion cargada"},
            {"music.loading", "Cargando..."},
            {"music.download_song", "Descargar cancion"},
            {"music.song_downloaded", "¡Cancion descargada!"},
            {"music.enter_song_id", "Ingresa un ID de cancion"},
            {"music.invalid_song_id", "ID de cancion invalido"},
            {"music.load_error", "No se pudo cargar info. Verifica el ID."},
            {"music.waveform_error", "No se pudo analizar la forma de onda"},
            {"music.download_error", "Error al descargar cancion"},
            {"music.fragment_too_long", "El fragmento no puede exceder 20 segundos"},
            {"music.fragment_too_short", "El fragmento debe ser al menos 5 segundos"},
            {"music.save_error", "Error al guardar: {}"},
            {"music.saved", "¡Musica de perfil guardada!"},
            {"music.delete_confirm", "¿Eliminar musica de perfil?"},
            {"music.deleted", "Musica de perfil eliminada"},
            {"music.own_profile_only", "Solo puedes configurar musica en tu propio perfil"},
            {"music.volume", "Volumen:"},
            {"music.selection", "Seleccion:"},

            // PaiConfigLayer
            {"pai.config.title", "Configuracion de Paimon"},
            {"pai.config.tab.backgrounds", "Fondos"},
            {"pai.config.tab.profile", "Perfil"},
            {"pai.config.tab.extras", "Extras"},
            {"pai.config.apply", "Aplicar y Reiniciar Menu"},
            {"pai.config.preview", "Vista previa"},
            {"pai.config.background.title", "Fondo"},
            {"pai.config.background.info.title", "Fondo"},
            {"pai.config.background.info.body", "<cy>Imagen personalizada</c>: PNG/JPG/GIF local.\n<cy>Aleatorio</c>: Miniatura en cache.\n<cy>Mismo que/Set ID/Defecto</c>: Otras fuentes.\n<cy>Oscuro</c>: Overlay + <cy>Adaptivo</c> (Menu)."},
            {"pai.config.background.custom_image", "Imagen personalizada"},
            {"pai.config.background.random", "Aleatorio"},
            {"pai.config.background.same_as", "Mismo que..."},
            {"pai.config.background.default", "Defecto"},
            {"pai.config.background.level_id", "ID de nivel"},
            {"pai.config.background.set", "Aplicar"},
            {"pai.config.background.dark", "Oscuro"},
            {"pai.config.background.intensity", "Intensidad"},
            {"pai.config.background.adaptive_colors", "Colores adaptivos"},
            {"pai.config.background.shader", "Shader:"},
            {"pai.config.background.blocked_message", "Level Info usa su propio\nfondo de miniatura.\n\nCambia en Mod Settings\n> Background Style."},
            {"pai.config.status.default", "Defecto"},
            {"pai.config.status.custom_image", "Imagen personalizada"},
            {"pai.config.status.random", "Aleatorio"},
            {"pai.config.status.level_id", "ID de nivel: "},
            {"pai.config.status.same_as_menu", "Mismo que Menu"},
            {"pai.config.profile.title", "Foto de perfil"},
            {"pai.config.profile.info.title", "Perfil"},
            {"pai.config.profile.info.body", "<cy>Set Image</c>: Elige una imagen local.\n<cy>Clear</c>: Quita la imagen personalizada.\n<cy>Photo Shape</c>: Edita forma, borde y efectos.\nLa vista previa se actualiza al instante."},
            {"pai.config.profile.set_image", "Set Image"},
            {"pai.config.profile.clear_image", "Clear Image"},
            {"pai.config.profile.photo_shape", "Photo Shape"},
            {"pai.config.profile.no_image", "Sin\nimagen"},
            {"pai.config.extras.title", "Extras"},
            {"pai.config.extras.pet_config", "Config de Mascota"},
            {"pai.config.extras.custom_cursor", "Cursor Personalizado"},
            {"pai.config.extras.beta", "BETA"},
            {"pai.config.extras.pet_info.title", "Mascota"},
            {"pai.config.extras.pet_info.body", "Una mascota sigue tu cursor.\nEsta funcion esta en <cr>BETA</c> y puede tener errores."},
            {"pai.config.extras.custom_cursor_info.title", "Cursor Personalizado"},
            {"pai.config.extras.custom_cursor_info.body", "Abre el editor completo del cursor personalizado.\nDesde ahi puedes anadir imagenes, asignar slots idle/move\ny ajustar escala, opacidad, trail y capas activas."},
            {"pai.config.extras.transitions", "Transiciones"},
            {"pai.config.extras.transitions_info.title", "Transiciones"},
            {"pai.config.extras.transitions_info.body", "Configura efectos personalizados de transicion de escena.\nElige entre 15+ transiciones o crea la tuya\ncon una secuencia personalizada (DSL)."},
            {"pai.config.extras.clear_cache", "Limpiar toda la cache"},
            {"pai.config.extras.clear_cache_info.title", "Limpiar cache"},
            {"pai.config.extras.clear_cache_info.body", "<cr>Elimina TODOS los datos cacheados:</c>\n- Miniaturas descargadas (RAM + disco)\n- Miniaturas e imagenes de perfil\n- Cache de musica de perfil\n- Cache GIF (RAM + disco)\n- Configuracion de fondos de perfil\n\nEsto libera espacio y corrige datos viejos.\nTodo se volvera a descargar cuando haga falta."},
            {"pai.config.extras.coming_soon", "Mas funciones pronto..."},
            {"pai.config.shader.none", "Ninguno"},
            {"pai.config.shader.grayscale", "Escala de grises"},
            {"pai.config.shader.sepia", "Sepia"},
            {"pai.config.shader.vignette", "Vinetta"},
            {"pai.config.shader.bloom", "Bloom"},
            {"pai.config.shader.chromatic", "Cromatico"},
            {"pai.config.shader.pixelate", "Pixelado"},
            {"pai.config.shader.posterize", "Posterizado"},
            {"pai.config.shader.scanlines", "Scanlines"},
            {"pai.config.preview.default_bg", "Fondo GD\ndefecto"},
            {"pai.config.preview.file_not_found", "Archivo no\nencontrado"},
            {"pai.config.preview.gif_error", "Error GIF"},
            {"pai.config.preview.load_error", "Error de\ncarga"},
            {"pai.config.preview.not_found_server", "No encontrado\nen servidor"},
            {"pai.config.preview.random_no_cache", "Aleatorio\n(sin cache)"},
            {"pai.config.preview.unknown_type", "Tipo\ndesconocido"},
            {"pai.config.notify.custom_image_set", "Imagen personalizada aplicada!"},
            {"pai.config.notify.random_set", "Fondo aleatorio aplicado!"},
            {"pai.config.notify.level_id_set", "ID de nivel aplicado!"},
            {"pai.config.notify.invalid_id", "ID invalido"},
            {"pai.config.notify.same_as_prefix", "Usando el mismo fondo que "},
            {"pai.config.notify.reverted_default", "Restaurado a defecto!"},
            {"pai.config.notify.profile_image_set", "Imagen de perfil aplicada!"},
            {"pai.config.notify.profile_image_cleared", "Imagen de perfil limpiada!"},
            {"pai.config.notify.cache_cleared", "Toda la cache fue limpiada!"},
            {"pai.config.clear_cache.title", "Limpiar toda la cache"},
            {"pai.config.clear_cache.message", "Esto <cr>eliminara todos los datos cacheados</c>:\nminiaturas, imagenes de perfil, musica de perfil,\nGIFs y configuracion de fondo de perfil.\n\nEstas seguro?"},
            {"pai.config.clear_cache.confirm", "Limpiar"},

            // CaptureAssetBrowserPopup
            {"assets.title", "Explorador de Assets"},
            {"assets.no_objects", "No se encontraron objetos"},
            {"assets.no_playlayer", "PlayLayer no disponible"},
            {"assets.restore_all", "Restaurar"},
            {"assets.restored", "Assets restaurados"},
            {"assets.hide_all", "Ocultar todo"},
            {"assets.show_all", "Mostrar todo"},
            {"assets.done", "Listo"},
            {"assets.count_fmt", "x{}"},
            {"assets.cat_blocks", "Bloques"},
            {"assets.cat_spikes", "Pinchos"},
            {"assets.cat_deco", "Decoracion"},
            {"assets.cat_triggers", "Triggers"},
            {"assets.cat_portals", "Portales"},
            {"assets.cat_special", "Especial"},
            {"assets.cat_other", "Otros"},

            // ProfileSettingsPopup
            {"profilesettings.title", "Ajustes de Perfil"},
            {"profilesettings.music_label", "Musica"},
            {"profilesettings.badge_label", "Insignia"},
            {"profilesettings.image_label", "Fondo Perfil"},
            {"profilesettings.comment_label", "Comentario"},
            {"profilesettings.info_title", "Ajustes de Perfil"},
            {"profilesettings.info_body", "<cj>Musica</c>: Cancion de perfil.\n<cg>Fondo Perfil</c>: Imagen o video personalizado.\n<cy>Insignia</c>: Personaliza tu insignia de perfil.\n<cr>Comentario</c>: Fondo de tus comentarios."},
            {"profilesettings.comment_soon_title", "Proximamente"},
            {"profilesettings.comment_soon_body", "La personalizacion de comentarios estara disponible en la version <cy>1.0.1</c>."},
            {"profilesettings.info_ok", "OK"},

            // PauseLayer video
            {"pause.video_open_error", "Error al abrir archivo de video"},
            {"pause.video_too_large", "Video demasiado grande (max 50MB)"},
            {"pause.video_mods_only", "Solo moderadores/admins pueden subir videos"},
            {"pause.video_uploading", "Subiendo video..."},
            {"pause.video_success", "Video subido exitosamente"},
            {"pause.video_upload_error", "Error al subir video"},
            {"pause.render_error", "Failed to create render texture"},
            {"pause.render_read_error", "Failed to read rendered image"},

            // ProfilePage
            {"profile.cant_rate_own", "No puedes calificar tu propio perfil!"},

            // PaimonHubLayer
            {"pai.hub.title", "Paimbnails"},
            {"pai.hub.tab.home", "Inicio"},
            {"pai.hub.tab.news", "Noticias"},
            {"pai.hub.tab.forum", "Foro"},
            {"pai.hub.welcome", "Bienvenido a Paimbnails!"},
            {"pai.hub.description", "Personaliza tu experiencia en Geometry Dash"},
            {"pai.hub.btn.config", "Configuracion"},
            {"pai.hub.btn.language", "Idioma"},
            {"pai.hub.btn.profiles", "Perfiles"},
            {"pai.hub.btn.backgrounds", "Fondos"},
            {"pai.hub.btn.extras", "Extras"},
            {"pai.hub.btn.support", "Soporte"},
            {"pai.hub.news.title", "Ultimas Noticias"},
            {"pai.hub.news.refresh", "Actualizar"},
            {"pai.hub.news.refreshed", "Noticias actualizadas!"},
            {"pai.hub.news.item1.title", "Bienvenido a Paimbnails!"},
            {"pai.hub.news.item1.desc", "Explora nuestro nuevo hub con secciones de noticias y foro."},
            {"pai.hub.news.item2.title", "Version 1.0.1 Lanzada"},
            {"pai.hub.news.item2.desc", "Nuevas funciones y correcciones de errores ya disponibles."},
            {"pai.hub.news.item3.title", "Perfiles Personalizados"},
            {"pai.hub.news.item3.desc", "Crea y comparte tus fotos de perfil personalizadas."},
            {"pai.hub.forum.title", "Foro Comunitario"},
            {"pai.hub.forum.create", "+ Nuevo Post"},
            {"pai.hub.forum.tags", "Etiquetas:"},
            {"pai.hub.forum.no_posts", "No hay posts aun. Se el primero en crear uno!"},
            {"pai.hub.forum.create_post", "Crear Nuevo Post"},
            {"pai.hub.forum.title_placeholder", "Titulo"},
            {"pai.hub.forum.desc_placeholder", "Descripcion"},
            {"pai.hub.forum.tag_placeholder", "Etiqueta"},
            {"pai.hub.forum.post", "Publicar"},
            {"pai.hub.forum.create_tag", "Crear Etiqueta Personalizada"},
            {"pai.hub.forum.new_tag", "Nombre de etiqueta"},
            // Update system
            {"pai.hub.btn.update", "Buscar actualizacion"},
            {"pai.hub.version", "Version: {}"},
            {"pai.update.title", "Descargando actualizacion"},
            {"pai.update.checking", "Buscando actualizaciones..."},
            {"pai.update.starting", "Iniciando..."},
            {"pai.update.cancel", "Cancelar"},
            {"pai.update.restart", "Reiniciar"},
            {"pai.update.close", "Cerrar"},
            {"pai.update.done", "Actualizacion instalada. Reinicia para aplicar."},
            {"pai.update.failed", "Error"},
            {"pai.update.uptodate", "Ya tienes la ultima version!"}
        };

        // English translations
        m_english = {
            // CapturePreviewPopup
            {"preview.title", "Preview"},
            {"preview.borders_removed", "Borders already removed"},
            {"preview.no_borders", "No black borders detected"},
            {"preview.borders_deleted", "Borders deleted"},
            {"preview.fill_mode_active", "Fill (active)"},
            {"preview.fit_mode_active", "Fit (active)"},
            {"preview.player_toggle_error", "Cannot toggle player visibility"},
            {"preview.no_image", "No image to download"},
            {"preview.folder_error", "Failed to create download folder"},
            {"preview.downloaded", "Thumbnail downloaded!"},
            {"preview.save_error", "Failed to save file"},
            {"preview.process_error", "Failed to process image"},
            {"preview.res_changed", "Resolution changed to {}"},
            {"preview.recapturing", "Recapturing..."},

            // CaptureEditPopup
            {"edit.capture_title", "Edit"},
            {"edit.toggle_player", "Hide player"},
            {"edit.hide_player1", "Hide P1"},
            {"edit.show_player1", "Show P1"},
            {"edit.hide_player2", "Hide P2"},
            {"edit.show_player2", "Show P2"},
            {"edit.crop_borders", "Crop borders"},
            {"edit.toggle_fill", "View mode"},
            {"edit.download", "Download"},
            {"edit.edit_layers", "Edit layers"},

            // CaptureLayerEditorPopup
            {"layers.title", "Edit Layers"},
            {"layers.player1", "Player 1"},
            {"layers.player2", "Player 2"},
            {"layers.effects", "Effects (Shaders)"},
            {"layers.recapture", "Recapture"},
            {"layers.done", "Done"},
            {"layers.restore_all", "Restore"},
            {"layers.restored", "Layers restored"},
            {"layers.recapturing", "Recapturing..."},
            {"layers.recapture_error", "Failed to recapture"},
            {"layers.no_playlayer", "PlayLayer not available"},
            {"layers.beta_title", "Beta Feature"},
            {"layers.beta_message", "<cr>This feature is in beta</c> and may have <cy>many bugs</c>.\nSome layers may not work correctly.\n\nAre you sure you want to continue?"},
            {"layers.beta_confirm", "Continue"},
            {"layers.beta_cancel", "Cancel"},

            // Keybinds
            {"keybind.capture_triggered", "Capture triggered"},
            {"keybind.capture_paused", "Cannot capture while paused"},

            // PlayLayer & PauseLayer
            {"capture.action_name", "Capture Thumbnail"},
            {"capture.action_desc", "Takes a screenshot of the current level"},
            {"capture.error", "Failed to capture thumbnail"},
            {"capture.process_error", "Failed to process thumbnail"},
            {"capture.save_png_error", "Failed to save PNG"},
            {"capture.read_png_error", "Failed to read PNG"},
            {"capture.upload_error", "Failed to upload thumbnail"},
            {"capture.uploading", "Uploading thumbnail to server..."},
            {"capture.upload_success", "Thumbnail uploaded successfully!"},
            {"capture.suggested", "Thumbnail suggested"},
            {"capture.verifying", "Verifying permissions..."},
            {"capture.uploading_suggestion", "Uploading suggestion..."},

            // PauseLayer specific
            {"pause.no_local_thumb", "No local thumbnail to upload"},
            {"pause.only_moderators", "Only moderators can upload thumbnails"},
            {"pause.access_error", "Failed to access local thumbnail"},
            {"pause.read_error", "Failed to read local thumbnail"},
            {"pause.gif_disabled", "GIF recording temporarily disabled"},
            {"pause.playlayer_error", "Error: PlayLayer not available"},
            {"pause.capture_error", "Failed to start capture"},
            {"pause.gif_open_error", "Error: Could not open GIF"},
            {"pause.gif_read_error", "Error: Could not read GIF"},
            {"pause.gif_texture_error", "Error: Could not create GIF texture"},
            {"pause.gif_uploading", "Uploading GIF to server..."},
            {"pause.gif_uploaded", "GIF uploaded successfully"},
            {"pause.gif_upload_error", "Failed to upload GIF"},
            {"pause.gif_process_error", "Failed to process GIF"},
            {"pause.file_open_error", "Error: Could not open file"},
            {"pause.png_invalid", "Error: Invalid PNG file"},
            {"pause.process_thumbnail_error", "Failed to process thumbnail"},

            // ProfilePage
            {"profile.username_error", "Could not get your username"},
            {"profile.verified", "Verified"},
            {"profile.verified_msg", "You are an <cg>approved moderator</c>! You can now upload and verify thumbnails."},
            {"profile.not_verified", "Not Verified"},
            {"profile.not_verified_msg", "You are not on the approved moderators list."},
            {"profile.image_open_error", "Could not open image"},
            {"profile.video_open_error", "Could not open video"},
            {"profile.texture_error", "Could not create texture"},
            {"profile.saved", "Profile thumbnail saved"},
            {"profile.no_image_selected", "No image selected"},
            {"profile.invalid_image_data", "Invalid image data"},
            {"profile.access_denied", "Access denied"},
            {"profile.moderators_only", "Only moderators can access the verification center."},

            // LevelInfoLayer
            {"level.title", "Level Thumbnail"},
            {"level.no_thumbnail", "No thumbnail"},
            {"level.open_error", "Failed to open thumbnail"},
            {"level.read_error", "Failed to read thumbnail"},
            {"level.create_error", "Failed to create image"},
            {"level.save_error", "Failed to save image"},
            {"level.saved", "Image saved successfully"},
            {"level.no_local", "No local thumbnail"},
            {"level.cant_open", "Could not open thumbnail"},
            {"level.corrupt", "Corrupt thumbnail"},
            {"level.report_button", "Report"},
            {"level.delete_button", "Delete thumbnail"},
            {"level.accept_button", "Accept"},
            {"level.download_button", "Download"},

            // VerificationQueuePopup
            {"queue.title", "Verification center"},
            {"queue.verify_tab", "verify thumbnails"},
            {"queue.update_tab", "update"},
            {"queue.report_tab", "reports"},
            {"queue.no_items", "No items"},
            {"queue.select_item", "Select an item"},
            {"queue.open_button", "Open"},
            {"queue.accept_button", "Accept"},
            {"queue.reject_button", "Reject"},
            {"queue.view_report", "View report"},
            {"queue.report_reason", "Report reason"},
            {"queue.close", "Close"},
            {"queue.no_local", "No local thumbnail"},
            {"queue.cant_open", "Could not open thumbnail"},
            {"queue.corrupt", "Corrupt thumbnail"},
            {"queue.read_error", "Failed to read thumbnail"},
            {"queue.create_error", "Failed to create image"},
            {"queue.png_error", "Failed to generate PNG"},
            {"queue.png_read_error", "Failed to read PNG"},
            {"queue.accepting", "Accepting and uploading to server..."},
            {"queue.accepted", "Thumbnail accepted and synced"},
            {"queue.accept_error", "Failed to sync with server"},
            {"queue.rejecting", "Rejecting on server..."},
            {"queue.rejected", "Thumbnail rejected and synced"},
            {"queue.reject_error", "Failed to sync rejection"},

            // AddModeratorPopup
            {"addmod.enter_username", "Enter a username"},
            {"addmod.success_title", "Added"},
            {"addmod.success_msg", "Moderator added successfully"},
            {"addmod.error_title", "Error"},
            {"addmod.error_msg", "Could not add moderator"},
            {"addmod.title", "Manage Moderators"},
            {"addmod.add_btn", "Add"},
            {"addmod.enter_username_label", "New moderator:"},
            {"addmod.loading_mods", "Loading moderators..."},
            {"addmod.no_mods", "No moderators found"},
            {"addmod.remove_btn", "Remove"},
            {"addmod.remove_confirm_title", "Remove Moderator"},
            {"addmod.remove_confirm_msg", "Remove <cy>{}</c> as moderator?"},
            {"addmod.remove_success", "Moderator removed successfully"},
            {"addmod.remove_error", "Could not remove moderator"},
            {"general.cancel", "Cancel"},

            // BulkUploadPopup
            {"bulk.title", "Bulk Upload"},
            {"bulk.select_folder_label", "Select a folder with thumbnails"},
            {"bulk.progress_label", "0 / 0 thumbnails"},
            {"bulk.info_text", "Files must follow this format:\nlevelID.png (e.g: 12345.png)\n\nOnly thumbnails for levels\nthat don't already have one will be uploaded."},
            {"bulk.scanning", "Scanning folder..."},

            // GIFUploadPopup
            {"gif.upload.title", "Recorded GIF"},
            {"gif.label", "GIF"},

            // SetDailyWeeklyPopup
            {"daily.title", "Set Featured Level"},
            {"daily.set_daily", "Set Daily"},
            {"daily.set_weekly", "Set Weekly"},
            {"daily.success_daily_title", "Success"},
            {"daily.success_daily_msg", "Level set as Daily!"},
            {"daily.error_daily_title", "Error"},
            {"daily.error_daily_msg", "Failed to set Daily level."},
            {"daily.success_weekly_title", "Success"},
            {"daily.success_weekly_msg", "Level set as Weekly!"},
            {"daily.error_weekly_title", "Error"},
            {"daily.error_weekly_msg", "Failed to set Weekly level."},

            // ThumbnailViewPopup
            {"thumbview.title", "Thumbnail"},

            // VerificationQueuePopup
            {"queue.banned_btn", "Banned"},
            {"queue.level_id", "Level {}"},
            {"queue.claimed_by_you", "Claimed by you"},
            {"queue.claimed_by_user", "Claimed by {}"},
            {"queue.view_btn", "View"},
            {"queue.view_thumb", "View Thumbnail"},
            {"queue.claim_btn", "Claim"},
            {"queue.unclaim_btn", "Unclaim"},
            {"queue.accept_btn", "Accept"},
            {"queue.reject_btn", "Reject"},
            {"queue.verified_by", "Verified by {}"},
            {"queue.reported_by", "Reported by {}"},
            {"queue.reason", "Reason: {}"},
            {"queue.ignore_btn", "Ignore"},
            {"queue.delete_btn", "Delete"},
            {"queue.keep_btn", "Keep"},
            {"queue.claiming", "Claiming level..."},
            {"queue.claimed", "Level claimed"},
            {"queue.claim_error", "Error: {}"},

            // ButtonEditOverlay
            {"edit.buttons_title", "Edit Buttons"},
            {"edit.accept", "Accept"},
            {"edit.reset", "Reset"},
            {"edit.scale", "Scale:"},
            {"edit.opacity", "Opacity:"},
            {"menu_layout.title", "Main Menu Layout Editor"},
            {"menu_layout.save", "Save"},
            {"menu_layout.cancel", "Cancel"},
            {"menu_layout.save_preset", "Save Slot"},
            {"menu_layout.load_preset", "Load Slot"},
            {"menu_layout.reset_selected", "Reset Button"},
            {"menu_layout.reset_all", "Reset All"},
            {"menu_layout.layers_title", "Layers"},
            {"menu_layout.layer", "Layer"},
            {"menu_layout.layer_up", "Raise"},
            {"menu_layout.layer_down", "Lower"},
            {"menu_layout.edit_selected", "Edit"},
            {"menu_layout.link_selected", "Link"},
            {"menu_layout.unlink_selected", "Unlink"},
            {"menu_layout.hide_selected", "Hide"},
            {"menu_layout.delete_selected", "Delete"},
            {"menu_layout.scale_down", "Size -"},
            {"menu_layout.scale_up", "Size +"},
            {"menu_layout.hint", "Drag to move. Green grip = locked scale. Scale button = free mode. Blue +/- = opacity. Size +/- = quick grow. Red X = hide/show. Esc cancels."},
            {"menu_layout.none_selected", "Tap any main menu button to edit it"},
            {"menu_layout.status", "Button: {}  X:{:.0f} Y:{:.0f}  Scale:{:.2f}x  Opacity:{:.0f}%"},
            {"menu_layout.saved", "Main menu layout saved"},
            {"menu_layout.context_popup_hint", "Adjust opacity, color, and font for the selected item."},
            {"menu_layout.context_font", "Font"},
            {"menu_layout.context_pick_font", "Pick"},
            {"menu_layout.presets_title_save", "Save Preset"},
            {"menu_layout.presets_title_load", "Load Preset"},
            {"menu_layout.presets_hint_save", "Pick a slot to save the current layout."},
            {"menu_layout.presets_hint_load", "Pick a slot to load the full layout."},
            {"menu_layout.presets_page", "Page {}/{}"},
            {"menu_layout.presets_slot", "Slot {}"},
            {"menu_layout.presets_empty", "Empty"},
            {"menu_layout.presets_items", "{} items"},
            {"menu_layout.presets_empty_slot", "That slot is empty"},
            {"menu_layout.preset_saved", "Preset saved to slot {}"},
            {"menu_layout.preset_loaded", "Preset loaded from slot {}"},
            {"menu_layout.preset_overwrite_title", "Overwrite Preset"},
            {"menu_layout.preset_overwrite_body", "Slot <cy>{}</c> already has a preset. Overwrite it?"},
            {"menu_layout.preset_overwrite_confirm", "Overwrite"},
            {"menu_layout.preset_load_title", "Load Preset"},
            {"menu_layout.preset_load_body", "Load the preset from slot <cy>{}</c>? This will replace the editor's current layout."},
            {"menu_layout.preset_load_confirm", "Load"},
            {"menu_layout.reset_done", "Buttons restored to their base layout"},
            {"menu_layout.reset_saved", "Saved layout cleared and buttons restored"},
            {"menu_layout.draw_add_rect", "Rect"},
            {"menu_layout.draw_add_round", "Round"},
            {"menu_layout.draw_add_circle", "Circle"},
            {"menu_layout.draw_edit_shape", "Edit Draw"},
            {"menu_layout.draw_shape_label", "Paimon Draw"},
            {"menu_layout.draw_shape_popup_title", "Edit Paimon Draw"},
            {"menu_layout.draw_shape_popup_hint", "Adjust shape, color, size, and opacity. It is saved in the layout and preset slots."},
            {"menu_layout.draw_shape_kind", "Shape"},
            {"menu_layout.draw_shape_kind_rect", "Rectangle"},
            {"menu_layout.draw_shape_kind_round", "Rounded"},
            {"menu_layout.draw_shape_kind_circle", "Circle"},
            {"menu_layout.draw_shape_cycle", "Cycle"},
            {"menu_layout.draw_shape_color", "Color"},
            {"menu_layout.draw_shape_pick_color", "Pick"},
            {"menu_layout.draw_shape_width", "Width"},
            {"menu_layout.draw_shape_height", "Height"},
            {"menu_layout.draw_shape_radius", "Radius"},
            {"menu_layout.draw_shape_opacity", "Opacity"},
            {"menu_layout.draw_shape_radius_disabled", "N/A"},

            // ForYou
            {"foryou.title", "For You"},
            {"foryou.tab", "For You"},
            {"foryou.not_enough_data", "Play more levels to unlock recommendations"},
            {"foryou.no_results", "No recommended levels found"},
            {"foryou.tags_prompt_title", "Level Tags"},
            {"foryou.tags_prompt", "Install <cy>Level Tags</c> to improve your recommendations with level tags!"},
            {"foryou.tags_download", "Download"},
            {"foryou.fav_creator_added", "Creator added to favorites"},
            {"foryou.fav_creator_removed", "Creator removed from favorites"},
            {"foryou.fav_level_added", "Level added to favorites"},
            {"foryou.fav_level_removed", "Level removed from favorites"},
            {"foryou.prefs_title", "What levels do you like?"},
            {"foryou.prefs_subtitle", "Choose your preferences to improve recommendations"},
            {"foryou.prefs_difficulty", "Difficulty"},
            {"foryou.prefs_gamemode", "Game Mode"},
            {"foryou.prefs_classic", "Classic"},
            {"foryou.prefs_platformer", "Platformer"},
            {"foryou.prefs_both", "Both"},
            {"foryou.prefs_confirm", "Confirm"},
            {"foryou.prefs_length", "Length"},
            {"foryou.prefs_tiny", "Tiny"},
            {"foryou.prefs_short", "Short"},
            {"foryou.prefs_medium", "Medium"},
            {"foryou.prefs_long", "Long"},
            {"foryou.prefs_xl", "XL"},
            {"foryou.prefs_any_length", "Any"},
            {"foryou.prefs_star_rated", "Star-rated"},
            {"foryou.prefs_featured", "Featured"},
            {"foryou.prefs_epic", "Epic"},
            {"foryou.prefs_demon_diff", "Demon Diff"},
            {"foryou.prefs_filters", "Filters"},
            {"foryou.info_difficulty_title", "Difficulty"},
            {"foryou.info_difficulty_desc", "Pick the <cy>difficulty</c> you prefer.\nAffects the levels shown in your\n<cg>For You</c> feed."},
            {"foryou.info_demon_title", "Demon Difficulty"},
            {"foryou.info_demon_desc", "Only applies if you selected <cy>Demon</c> above.\nPick your preferred sub-difficulty:\n<cy>Easy, Medium, Hard, Insane, Extreme</c>\nor <cg>Any</c> to skip this filter."},
            {"foryou.info_mode_title", "Game Mode"},
            {"foryou.info_mode_desc", "<cy>Classic</c>: traditional levels.\n<cy>Platformer</c>: platformer-style levels.\n<cy>Both</c>: no mode preference."},
            {"foryou.info_length_title", "Length"},
            {"foryou.info_length_desc", "Approximate level duration:\n<cy>Tiny, Short, Medium, Long, XL</c>\nor <cg>Any</c> to skip this filter."},
            {"foryou.info_filters_title", "Quality Filters"},
            {"foryou.info_filters_desc", "<cy>Star-rated</c>: rated levels.\n<cy>Featured</c>: featured levels.\n<cy>Epic</c>: levels with Epic rating."},
            {"foryou.prefs_rating", "Rating"},
            {"foryou.prefs_rating_star", "Star-rated"},
            {"foryou.prefs_rating_featured", "Featured"},
            {"foryou.prefs_rating_epic", "Epic"},
            {"foryou.prefs_rating_legendary", "Legendary"},
            {"foryou.prefs_rating_mythic", "Mythic"},
            {"foryou.info_rating_title", "Level Rating"},
            {"foryou.info_rating_desc", "Tap the icon to cycle through rating tiers:\n<cy>Star-rated</c> → <cy>Featured</c> → <cy>Epic</c> →\n<cy>Legendary</c> → <cy>Mythic</c>.\nEach tier includes the ones before it."},
            {"foryou.fav_levels_title", "Favorite Levels"},
            {"foryou.coming_soon", "Coming soon"},

            // LeaderboardsLayer
            {"leaderboard.daily", "Daily"},
            {"leaderboard.weekly", "Weekly"},
            {"leaderboard.all_time", "All Time"},
            {"leaderboard.creators", "Creators"},
            {"leaderboard.error", "Error"},
            {"leaderboard.read_error", "Failed to read response"},
            {"leaderboard.load_error", "Failed to load leaderboard: {}"},
            {"leaderboard.parse_error", "Failed to parse JSON"},
            {"leaderboard.server_error", "Server error"},
            {"leaderboard.invalid_format", "Invalid data format"},
            {"leaderboard.loading", "Loading..."},
            {"leaderboard.unknown", "Unknown"},
            {"mods.title", "Paimbnails Moderators"},

            // CommunityHubLayer
            {"community.title", "Community Hub"},
            {"community.tab_mods", "Moderators"},
            {"community.tab_creators", "Top Creators"},
            {"community.tab_thumbnails", "Top Thumbnails"},
            {"community.tab_compat_mods", "Compat. Mods"},
            {"community.compat_mods_title", "Compatible Mods"},
            {"community.compat_mods_version", "Available for version 1.0.1"},
            {"community.compat_mods_desc", "List of mods compatible with Paimbnails"},
            {"community.compat_mods_soon", "More mods coming soon..."},
            // CommunityHub info buttons
            {"community.info_mods_title", "Moderators"},
            {"community.info_mods_body", "List of official <cy>Paimbnails moderators</c>.\nThey can upload, verify and manage thumbnails.\n<cr>Admins</c> have additional permissions."},
            {"community.info_creators_title", "Top Creators"},
            {"community.info_creators_body", "Ranking of creators with the most uploaded and best-rated thumbnails.\nUpload thumbnails for your levels to appear on this list!"},
            {"community.info_thumbs_title", "Top Thumbnails"},
            {"community.info_thumbs_body", "The highest-rated thumbnails by the community.\nYou can vote on thumbnails from the level info screen."},
            {"community.info_compat_title", "Compatible Mods"},
            {"community.info_compat_body", "Geometry Dash mods compatible with Paimbnails.\nAvailable starting from version <cy>1.0.1</c>."},
            {"community.loading", "Loading..."},
            {"community.error", "Failed to load data"},
            {"community.no_data", "No data available"},
            {"community.uploads", "Uploads"},
            {"community.avg_rating", "Avg. Rating"},
            {"community.rating", "Rating"},
            {"community.votes", "Votes"},
            {"community.by", "by"},
            {"community.admin", "Admin"},
            {"community.mod", "Mod"},
            {"community.level", "Level"},
            {"leaderboard.no_refreshes", "No more refreshes available today!"},
            {"leaderboard.no_gamemanager", "Could not get GameManager"},
            {"leaderboard.empty_username", "Empty username"},
            {"leaderboard.no_image", "No image selected"},
            {"leaderboard.png_open_error", "Could not open PNG"},
            {"leaderboard.profile_saved_local", "Profile saved locally (server upload disabled)"},
            {"leaderboard.uploading_profile", "Uploading profile..."},
            {"leaderboard.profile_uploaded", "Profile uploaded"},
            {"leaderboard.profile_error", "Failed to upload profile"},
            {"leaderboard.unknown_error", "Unknown error"},
            {"leaderboard.synced", "Synced with server!"},

            // GIFRecordSettingsPopup
            {"gif.start", "Start"},

            // General
            {"general.error", "Error"},
            {"general.ok", "OK"},
            {"general.close", "Close"},

            // Missing keys added
            {"level.no_thumbnail_text", "No thumbnail"},
            {"level.saving_mod_folder", "Saving to mod folder..."},
            {"level.error_prefix", "Error: "},
            {"level.delete_moderator_only", "Only moderators can delete thumbnails"},
            {"level.deleting_server", "Deleting thumbnail from server..."},
            {"level.deleted_server", "Thumbnail deleted from server"},
            {"level.delete_error", "Error deleting: "},
            {"level.accepting", "Accepting thumbnail..."},
            {"level.accepted", "Thumbnail accepted!"},
            {"level.accept_error", "Error accepting: "},
            {"level.no_local_thumb", "No local thumbnail"},
            {"level.png_error", "Error generating PNG"},
            {"level.saved_local_server_disabled", "Thumbnail saved locally (server disabled)"},
            {"level.account_required", "You need an account to upload"},
            {"level.no_permissions", "You don't have permissions"},
            {"level.admin_only_high_votes", "Only admins can delete thumbnails with 100+ votes"},
            {"level.confirm_delete_title", "Delete Thumbnail"},
            {"level.confirm_delete_msg", "Are you sure you want to delete this thumbnail? This will also remove the creator's rating points."},
            {"level.thumbnail_deleted", "Thumbnail deleted"},

            // Report Popup
            {"report.title", "Report Thumbnail"},
            {"report.cancel", "Cancel"},
            {"report.send", "Send"},
            {"report.placeholder", "Write here..."},
            {"report.empty_reason", "You must specify a reason"},
            {"report.sent_synced", "Report sent and synced: "},
            {"report.saved_local", "Report saved locally (offline)"},

            // PauseLayer
            {"pause.gif_not_supported", "GIF files not supported on this platform"},
            {"pause.process_image_error", "Error: Could not process image"},
            {"pause.create_texture_error", "Error: Could not create texture"},
            {"pause.init_texture_error", "Error: Could not initialize texture"},
            {"pause.username_error", "Error: Could not get username"},
            {"pause.gif_recording_started", "GIF recording started"},

            // Ban System
            {"ban.list.title", "Banned Users"},
            {"ban.list.loading", "Loading..."},
            {"ban.list.empty", "No bans"},
            {"ban.list.unban_btn", "Unban"},
            {"ban.info.no_info", "No information available."},
            {"ban.info.reason", "Reason"},
            {"ban.info.by", "By"},
            {"ban.info.date", "Date"},
            {"ban.info.title", "Ban Details"},
            {"ban.unban.title", "Unban User"},
            {"ban.unban.confirm", "Are you sure you want to unban <cy>{}</c>?"},
            {"ban.unban.success", "User unbanned"},
            {"ban.unban.error", "Error unbanning"},
            {"ban.popup.title", "Ban User"},
            {"ban.popup.user", "User: {}"},
            {"ban.popup.placeholder", "Ban reason..."},
            {"ban.popup.ban_btn", "Ban"},
            {"ban.popup.enter_reason", "Enter a reason"},
            {"ban.popup.success", "User banned"},
            {"ban.popup.error", "Error banning"},
            {"ban.profile.mod_only", "Moderators/Admins only"},
            {"ban.profile.self_ban", "You cannot ban yourself"},
            {"ban.profile.read_error", "Could not read username"},

            // Profile Music
            {"music.title", "Profile Music"},
            {"music.load_song", "Load"},
            {"music.play_preview", "Play"},
            {"music.stop_preview", "Stop"},
            {"music.save", "Save"},
            {"music.delete", "Delete"},
            {"music.song_id_placeholder", "Song ID..."},
            {"music.no_song_loaded", "No song loaded"},
            {"music.loading", "Loading..."},
            {"music.download_song", "Download song"},
            {"music.song_downloaded", "Song downloaded!"},
            {"music.enter_song_id", "Please enter a song ID"},
            {"music.invalid_song_id", "Invalid song ID"},
            {"music.load_error", "Could not load song info. Check the ID."},
            {"music.waveform_error", "Could not analyze song waveform"},
            {"music.download_error", "Failed to download song"},
            {"music.fragment_too_long", "Fragment cannot exceed 20 seconds"},
            {"music.fragment_too_short", "Fragment must be at least 5 seconds"},
            {"music.save_error", "Failed to save: {}"},
            {"music.saved", "Profile music saved!"},
            {"music.delete_confirm", "Delete profile music?"},
            {"music.deleted", "Profile music deleted"},
            {"music.own_profile_only", "You can only configure music on your own profile"},
            {"music.volume", "Volume:"},
            {"music.selection", "Selection:"},

            // PaiConfigLayer
            {"pai.config.title", "Paimon Settings"},
            {"pai.config.tab.backgrounds", "Backgrounds"},
            {"pai.config.tab.profile", "Profile"},
            {"pai.config.tab.extras", "Extras"},
            {"pai.config.apply", "Apply & Restart Menu"},
            {"pai.config.preview", "Preview"},
            {"pai.config.background.title", "Background"},
            {"pai.config.background.info.title", "Background"},
            {"pai.config.background.info.body", "<cy>Custom Image</c>: Local PNG/JPG/GIF.\n<cy>Random</c>: Cached thumbnail.\n<cy>Same as/Set ID/Default</c>: Other sources.\n<cy>Dark</c>: Overlay + <cy>Adaptive</c> (Menu)."},
            {"pai.config.background.custom_image", "Custom Image"},
            {"pai.config.background.random", "Random"},
            {"pai.config.background.same_as", "Same as..."},
            {"pai.config.background.default", "Default"},
            {"pai.config.background.level_id", "Level ID"},
            {"pai.config.background.set", "Set"},
            {"pai.config.background.dark", "Dark"},
            {"pai.config.background.intensity", "Intensity"},
            {"pai.config.background.adaptive_colors", "Adaptive Colors"},
            {"pai.config.background.shader", "Shader:"},
            {"pai.config.background.blocked_message", "Level Info uses its own\nthumbnail background.\n\nChange in Mod Settings\n> Background Style."},
            {"pai.config.status.default", "Default"},
            {"pai.config.status.custom_image", "Custom Image"},
            {"pai.config.status.random", "Random"},
            {"pai.config.status.level_id", "Level ID: "},
            {"pai.config.status.same_as_menu", "Same as Menu"},
            {"pai.config.profile.title", "Profile Picture"},
            {"pai.config.profile.info.title", "Profile"},
            {"pai.config.profile.info.body", "<cy>Set Image</c>: Pick a local image.\n<cy>Clear</c>: Remove custom image.\n<cy>Photo Shape</c>: Edit shape, border, effects.\nPreview updates in real-time."},
            {"pai.config.profile.set_image", "Set Image"},
            {"pai.config.profile.clear_image", "Clear Image"},
            {"pai.config.profile.photo_shape", "Photo Shape"},
            {"pai.config.profile.no_image", "No\nImage"},
            {"pai.config.extras.title", "Extras"},
            {"pai.config.extras.pet_config", "Pet Config"},
            {"pai.config.extras.custom_cursor", "Custom Cursor"},
            {"pai.config.extras.beta", "BETA"},
            {"pai.config.extras.pet_info.title", "Pet"},
            {"pai.config.extras.pet_info.body", "A cute pet follows your cursor.\nThis feature is in <cr>BETA</c> — expect bugs!"},
            {"pai.config.extras.custom_cursor_info.title", "Custom Cursor"},
            {"pai.config.extras.custom_cursor_info.body", "Open the full custom cursor editor.\nFrom there you can add images, assign idle/move slots,\nand tweak scale, opacity, trail, and active layers."},
            {"pai.config.extras.transitions", "Transitions"},
            {"pai.config.extras.transitions_info.title", "Transitions"},
            {"pai.config.extras.transitions_info.body", "Configure custom scene transition effects.\nChoose from 15+ built-in transitions or create your own\nwith a custom command sequence (DSL)."},
            {"pai.config.extras.clear_cache", "Clear All Cache"},
            {"pai.config.extras.clear_cache_info.title", "Clear Cache"},
            {"pai.config.extras.clear_cache_info.body", "<cr>Deletes ALL cached data:</c>\n- Downloaded thumbnails (RAM + disk)\n- Profile thumbnails & images\n- Profile music cache\n- GIF cache (RAM + disk)\n- Profile background settings\n\nThis frees up space and fixes stale data.\nEverything will re-download as needed."},
            {"pai.config.extras.coming_soon", "More features coming soon..."},
            {"pai.config.shader.none", "None"},
            {"pai.config.shader.grayscale", "Grayscale"},
            {"pai.config.shader.sepia", "Sepia"},
            {"pai.config.shader.vignette", "Vignette"},
            {"pai.config.shader.bloom", "Bloom"},
            {"pai.config.shader.chromatic", "Chromatic"},
            {"pai.config.shader.pixelate", "Pixelate"},
            {"pai.config.shader.posterize", "Posterize"},
            {"pai.config.shader.scanlines", "Scanlines"},
            {"pai.config.preview.default_bg", "Default GD\nBackground"},
            {"pai.config.preview.file_not_found", "File not\nfound"},
            {"pai.config.preview.gif_error", "GIF Error"},
            {"pai.config.preview.load_error", "Load\nerror"},
            {"pai.config.preview.not_found_server", "Not found\non server"},
            {"pai.config.preview.random_no_cache", "Random\n(no cache)"},
            {"pai.config.preview.unknown_type", "Unknown\ntype"},
            {"pai.config.notify.custom_image_set", "Custom image set!"},
            {"pai.config.notify.random_set", "Random background set!"},
            {"pai.config.notify.level_id_set", "Level ID set!"},
            {"pai.config.notify.invalid_id", "Invalid ID"},
            {"pai.config.notify.same_as_prefix", "Using same bg as "},
            {"pai.config.notify.reverted_default", "Reverted to default!"},
            {"pai.config.notify.profile_image_set", "Profile image set!"},
            {"pai.config.notify.profile_image_cleared", "Profile image cleared!"},
            {"pai.config.notify.cache_cleared", "All caches cleared!"},
            {"pai.config.clear_cache.title", "Clear All Cache"},
            {"pai.config.clear_cache.message", "This will <cr>delete all cached data</c>:\nthumbnails, profile images, profile music,\nGIFs, and profile background settings.\n\nAre you sure?"},
            {"pai.config.clear_cache.confirm", "Clear"},

            // CaptureAssetBrowserPopup
            {"assets.title", "Asset Browser"},
            {"assets.no_objects", "No objects found"},
            {"assets.no_playlayer", "PlayLayer not available"},
            {"assets.restore_all", "Restore"},
            {"assets.restored", "Assets restored"},
            {"assets.hide_all", "Hide all"},
            {"assets.show_all", "Show all"},
            {"assets.done", "Done"},
            {"assets.count_fmt", "x{}"},
            {"assets.cat_blocks", "Blocks"},
            {"assets.cat_spikes", "Spikes"},
            {"assets.cat_deco", "Decoration"},
            {"assets.cat_triggers", "Triggers"},
            {"assets.cat_portals", "Portals"},
            {"assets.cat_special", "Special"},
            {"assets.cat_other", "Other"},

            // ProfileSettingsPopup
            {"profilesettings.title", "Profile Settings"},
            {"profilesettings.music_label", "Music"},
            {"profilesettings.badge_label", "Badge"},
            {"profilesettings.image_label", "Profile Background"},
            {"profilesettings.comment_label", "Comment"},
            {"profilesettings.info_title", "Profile Settings"},
            {"profilesettings.info_body", "<cj>Music</c>: Profile song.\n<cg>Profile Background</c>: Custom image or video.\n<cy>Badge</c>: Customize your profile badge.\n<cr>Comment</c>: Your comment background."},
            {"profilesettings.comment_soon_title", "Coming Soon"},
            {"profilesettings.comment_soon_body", "Comment background customization will be available in version <cy>1.0.1</c>."},
            {"profilesettings.info_ok", "OK"},

            // PauseLayer video
            {"pause.video_open_error", "Could not open video file"},
            {"pause.video_too_large", "Video too large (max 50MB)"},
            {"pause.video_mods_only", "Only moderators/admins can upload videos"},
            {"pause.video_uploading", "Uploading video..."},
            {"pause.video_success", "Video uploaded successfully"},
            {"pause.video_upload_error", "Error uploading video"},
            {"pause.render_error", "Failed to create render texture"},
            {"pause.render_read_error", "Failed to read rendered image"},

            // ProfilePage
            {"profile.cant_rate_own", "You can't rate your own profile!"},

            // PaimonHubLayer
            {"pai.hub.title", "Paimbnails"},
            {"pai.hub.tab.home", "Home"},
            {"pai.hub.tab.news", "News"},
            {"pai.hub.tab.forum", "Forum"},
            {"pai.hub.welcome", "Welcome to Paimbnails!"},
            {"pai.hub.description", "Customize your Geometry Dash experience"},
            {"pai.hub.btn.config", "Settings"},
            {"pai.hub.btn.language", "Language"},
            {"pai.hub.btn.profiles", "Profiles"},
            {"pai.hub.btn.backgrounds", "Backgrounds"},
            {"pai.hub.btn.extras", "Extras"},
            {"pai.hub.btn.support", "Support"},
            {"pai.hub.news.title", "Latest News"},
            {"pai.hub.news.refresh", "Refresh"},
            {"pai.hub.news.refreshed", "News refreshed!"},
            {"pai.hub.news.item1.title", "Welcome to Paimbnails!"},
            {"pai.hub.news.item1.desc", "Check out our new hub with news and forum sections."},
            {"pai.hub.news.item2.title", "Version 1.0.1 Released"},
            {"pai.hub.news.item2.desc", "New features and bug fixes are now available."},
            {"pai.hub.news.item3.title", "Custom Profiles"},
            {"pai.hub.news.item3.desc", "Create and share your custom profile pictures."},
            {"pai.hub.forum.title", "Community Forum"},
            {"pai.hub.forum.create", "+ New Post"},
            {"pai.hub.forum.tags", "Tags:"},
            {"pai.hub.forum.no_posts", "No posts yet. Be the first to create one!"},
            {"pai.hub.forum.create_post", "Create New Post"},
            {"pai.hub.forum.title_placeholder", "Title"},
            {"pai.hub.forum.desc_placeholder", "Description"},
            {"pai.hub.forum.tag_placeholder", "Tag"},
            {"pai.hub.forum.post", "Post"},
            {"pai.hub.forum.create_tag", "Create Custom Tag"},
            {"pai.hub.forum.new_tag", "Tag name"},
            // Update system
            {"pai.hub.btn.update", "Check for update"},
            {"pai.hub.version", "Version: {}"},
            {"pai.update.title", "Downloading update"},
            {"pai.update.checking", "Checking for updates..."},
            {"pai.update.starting", "Starting..."},
            {"pai.update.cancel", "Cancel"},
            {"pai.update.restart", "Restart"},
            {"pai.update.close", "Close"},
            {"pai.update.done", "Update installed. Restart to apply."},
            {"pai.update.failed", "Error"},
            {"pai.update.uptodate", "You're up to date!"}
        };

        m_portuguese = {
            {"pai.hub.tab.home", "Inicio"},
            {"pai.hub.tab.news", "Noticias"},
            {"pai.hub.tab.forum", "Forum"},
            {"pai.hub.welcome", "Bem-vindo ao Paimbnails!"},
            {"pai.hub.description", "Personalize sua experiencia no Geometry Dash"},
            {"pai.hub.btn.config", "Configuracoes"},
            {"pai.hub.btn.language", "Idioma"},
            {"pai.hub.btn.profiles", "Perfis"},
            {"pai.hub.btn.backgrounds", "Fundos"},
            {"pai.hub.btn.support", "Suporte"},
            {"pai.hub.btn.update", "Verificar atualizacao"},
        };

        m_french = {
            {"pai.hub.tab.home", "Accueil"},
            {"pai.hub.tab.news", "Actualites"},
            {"pai.hub.tab.forum", "Forum"},
            {"pai.hub.welcome", "Bienvenue sur Paimbnails!"},
            {"pai.hub.description", "Personnalisez votre experience Geometry Dash"},
            {"pai.hub.btn.config", "Parametres"},
            {"pai.hub.btn.language", "Langue"},
            {"pai.hub.btn.profiles", "Profils"},
            {"pai.hub.btn.backgrounds", "Fonds"},
            {"pai.hub.btn.support", "Support"},
            {"pai.hub.btn.update", "Verifier les mises a jour"},
        };

        m_german = {
            {"pai.hub.tab.home", "Start"},
            {"pai.hub.tab.news", "News"},
            {"pai.hub.tab.forum", "Forum"},
            {"pai.hub.welcome", "Willkommen bei Paimbnails!"},
            {"pai.hub.description", "Passe dein Geometry Dash Erlebnis an"},
            {"pai.hub.btn.config", "Einstellungen"},
            {"pai.hub.btn.language", "Sprache"},
            {"pai.hub.btn.profiles", "Profile"},
            {"pai.hub.btn.backgrounds", "Hintergrunde"},
            {"pai.hub.btn.support", "Support"},
            {"pai.hub.btn.update", "Nach Updates suchen"},
        };

        m_russian = {
            {"pai.hub.tab.home", "Главная"},
            {"pai.hub.tab.news", "Новости"},
            {"pai.hub.tab.forum", "Форум"},
            {"pai.hub.welcome", "Добро пожаловать в Paimbnails!"},
            {"pai.hub.description", "Настройте свой опыт Geometry Dash"},
            {"pai.hub.btn.config", "Настройки"},
            {"pai.hub.btn.language", "Язык"},
            {"pai.hub.btn.profiles", "Профили"},
            {"pai.hub.btn.backgrounds", "Фоны"},
            {"pai.hub.btn.support", "Поддержка"},
            {"pai.hub.btn.update", "Проверить обновления"},
        };

        m_japanese = {
            {"pai.hub.tab.home", "ホーム"},
            {"pai.hub.tab.news", "ニュース"},
            {"pai.hub.tab.forum", "フォーラム"},
            {"pai.hub.welcome", "Paimbnailsへようこそ!"},
            {"pai.hub.description", "Geometry Dash をもっと自分好みに"},
            {"pai.hub.btn.config", "設定"},
            {"pai.hub.btn.language", "言語"},
            {"pai.hub.btn.profiles", "プロフィール"},
            {"pai.hub.btn.backgrounds", "背景"},
            {"pai.hub.btn.support", "サポート"},
            {"pai.hub.btn.update", "アップデートを確認"},
        };
    }

    Language m_currentLanguage = Language::SPANISH;
    std::unordered_map<std::string, std::string> m_spanish;
    std::unordered_map<std::string, std::string> m_english;
    std::unordered_map<std::string, std::string> m_portuguese;
    std::unordered_map<std::string, std::string> m_french;
    std::unordered_map<std::string, std::string> m_german;
    std::unordered_map<std::string, std::string> m_russian;
    std::unordered_map<std::string, std::string> m_japanese;
};
